name: SSH Deployment
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          URL: ${{ secrets.URL }}

      - name: Deploy using rsync over SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" _site/ deploy@${{ secrets.VPS_HOST }}:/var/www/sites/${{ secrets.VPS_SITE_NAME }}/
