name: Ftp deployment
on:
  push:
    branches: [ master, staging ]


env:
  OCR_API_KEY: ${{ secrets.OCR_API_KEY }}

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Set env vars (staging)
        if: endsWith(github.ref, '/staging')
        run: |
          echo "NODE_ENV=development" >> $GITHUB_ENV
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/master')
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
      - uses: actions/checkout@master
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run build
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          URL: ${{ secrets.URL }}
      - name: FTP transfer to staging
        if: endsWith(github.ref, '/staging')
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_host }}
          port: ${{ secrets.ftp_port }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ${{ secrets.ftp_protocol }}
          local-dir: ${{ secrets.ftp_local_path }}
          server-dir: ${{ secrets.ftp_path_staging }}
      - name: FTP transfer to prod
        if: endsWith(github.ref, '/master')
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_host }}
          port: ${{ secrets.ftp_port }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ${{ secrets.ftp_protocol }}
          local-dir: ${{ secrets.ftp_local_path }}
          server-dir: ${{ secrets.ftp_path }}
